name: "amos"
version: "0.1.0"
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'amos') }}"

# Use environment variables to write to different databases, 
# if your data platform support supports it (eg. Snowflake, BigQuery)
# Otherwise (as with PostgreSQL), write to the current target database, defined in profiles.yml

sources:
  amos_source_example:
    +database: "{{ env_var('DBT_RAW_DATABASE', target.database) }}"

seeds:
  amos_source_example:
    +database: "{{ env_var('DBT_RAW_DATABASE', target.database) }}"
  amos_core:
    +database: "{{ env_var('DBT_CORE_DATABASE', target.database) }}"

models:
  amos_source_example:
    staging:
      +database: "{{ env_var('DBT_STAGING_DATABASE', target.database) }}"
    
    intermediate:
      +database: "{{ env_var('DBT_INTERMEDIATE_DATABASE', target.database) }}"
  amos_core:
    marts:
      +database: "{{ env_var('DBT_CORE_DATABASE', target.database) }}"
      

model-paths: ["models"]     # keep default
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  +quote_columns: false
  +full_refresh: true

vars:
  active_source: "example"   # toggle to another connector later

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"