name: "amos_runner"
version: "0.0.1"
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'amos_snowflake') }}"

# nothing to build in this repo; we build the imported packages
model-paths: ["models"]     # keep default
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  +quote_columns: false
  +full_refresh: true
  
  # Seed configurations are defined in each package's dbt_project.yml with sensible defaults.
  # Override them here if you need custom database/schema names for your environment.
  
  # Example: Override amos_source_example seed schemas
  # amos_source_example:
  #   crm_example:
  #     +schema: AMOS_CRM_EXAMPLE
  #   fund_admin_example:
  #     +schema: AMOS_FUND_ADMIN_EXAMPLE
  #   portfolio_management_example:
  #     +schema: AMOS_PM_EXAMPLE
  #   accounting_example:
  #     +schema: AMOS_ACCOUNTING_EXAMPLE
  #   shared_data_example:
  #     +schema: AMOS_SHARED_DATA_EXAMPLE
  
  # Example: Override amos_core seed schema
  # amos_core:
  #   +schema: REFERENCE

# No adapter-specific hooks; compatibility handled via macros in packages

vars:
  active_source: "example"   # toggle to another connector later