name: "amos_runner"
version: "0.0.1"
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'amos_snowflake') }}"

# nothing to build in this repo; we build the imported packages
model-paths: ["models"]     # keep default
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  +quote_columns: false
  +full_refresh: true
  
  # amos_source_example seeds - all load to RAW database
  amos_source_example:
    +database: "{{ env_var('DBT_RAW_DATABASE', 'RAW') }}"
    
    # CRM vendor seeds
    crm_vendor:
      +schema: AMOS_CRM_VENDOR
      +tags: ["crm", "seed", "raw"]
    
    # Fund admin vendor seeds
    fund_admin_vendor:
      +schema: AMOS_FUND_ADMIN_VENDOR
      +tags: ["fund_admin", "seed", "raw"]
    
    # Portfolio management vendor seeds
    portfolio_management_vendor:
      +schema: AMOS_PM_VENDOR
      +tags: ["portfolio_mgmt", "seed", "raw"]
    
    # Accounting vendor seeds
    accounting_vendor:
      +schema: AMOS_ACCOUNTING_VENDOR
      +tags: ["accounting", "seed", "raw"]
    
    # Reference data seeds
    reference:
      +schema: AMOS_REFERENCE
      +tags: ["reference", "seed", "raw"]
  
  # amos_core seeds - canonical reference data
  amos_core:
    +database: "{{ env_var('DBT_CANONICAL_DATABASE', 'CANONICAL') }}"
    +schema: REFERENCE
    +tags: ["reference", "seed", "canonical"]

# No adapter-specific hooks; compatibility handled via macros in packages

vars:
  active_source: "example"   # toggle to another connector later